### ISSUE TITLE
Elección de lenguaje de programación

### ISSUE THREAD

**Issue by lmchaves** [pablotl0/EnviroTrack#7]
Buenas, he abierto este issue elegir el lenguaje de programación, ¿tienes pensado alguno?

**Comment by pablotl0** [comment]
Hola, habia pensado en usar Go ya que  permite construir una aplicación escalable, eficiente y rápida para recopilar, procesar y distribuir datos.

**Comment by lmchaves** [comment]
Vale perfecto, yo también tenía pensado usar en mi proyecto.
