### ISSUE TITLE
¿Qué son los “datos de calidad del aire”?

### ISSUE THREAD

**Issue by lmchaves** [pablotl0/EnviroTrack#8]
En #2 , los datos de calidad del aire provienen de distintas fuentes y formatos, como PDF y Excel. Es crucial definir qué se entiende por "datos de calidad del aire" en este contexto, ¿Qué métricas componen los “datos de calidad del aire”? ¿Hay que considerar datos diarios, mensuales o anuales? ¿Es importante modelar la ubicación geográfica de los datos ?

**Comment by lmchaves** [comment]
Te parece correcta esta estructura para los datos de la calidad de aire, como usar una estrucutura adicional de FuenteDatos?

**Comment by JJ** [comment]
¿Cada uno de los commits cierra el problema?

**Comment by lmchaves** [comment]
En un principio, utilicé close porque el arhcivo era el cierre del probelma, pero al ir añadiendo modificacioens, se ve de esta manera. Sin embargo, a partir de ahora, solo usaré closes en el último commit relacionado, para mantenerlo más claro y coherente.
